name: shopping_cart_tom
description: E-Commerce mobile application that has a shopping cart functionality
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Dependency Injection, State Management
  provider: ^6.0.5

  #Network
  http : ^0.13.4

  #Animation
  rive: ^0.10.4

  #Local Storage
  shared_preferences: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700


  assets:
    - assets/
