import 'package:flutter/material.dart';

final lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: lightColorScheme,
  fontFamily: 'Poppins',
);

final darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: darkColorScheme,
  fontFamily: 'Poppins',
);

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF773BC8),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFEDDCFF),
  onPrimaryContainer: Color(0xFF280056),
  secondary: Color(0xFF006874),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFF97F0FF),
  onSecondaryContainer: Color(0xFF001F24),
  tertiary: Color(0xFF773BC8),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFEDDCFF),
  onTertiaryContainer: Color(0xFF280056),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1D1B1E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1D1B1E),
  surfaceVariant: Color(0xFFE8E0EB),
  onSurfaceVariant: Color(0xFF4A454E),
  outline: Color(0xFF7B757F),
  onInverseSurface: Color(0xFFF5EFF4),
  inverseSurface: Color(0xFF322F33),
  inversePrimary: Color(0xFFD7BAFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF773BC8),
  outlineVariant: Color(0xFFCBC4CF),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFD7BAFF),
  onPrimary: Color(0xFF440088),
  primaryContainer: Color(0xFF5E1AAF),
  onPrimaryContainer: Color(0xFFEDDCFF),
  secondary: Color(0xFF4FD8EB),
  onSecondary: Color(0xFF00363D),
  secondaryContainer: Color(0xFF004F58),
  onSecondaryContainer: Color(0xFF97F0FF),
  tertiary: Color(0xFFD7BAFF),
  onTertiary: Color(0xFF440088),
  tertiaryContainer: Color(0xFF5E1AAF),
  onTertiaryContainer: Color(0xFFEDDCFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1D1B1E),
  onBackground: Color(0xFFE7E1E6),
  surface: Color(0xFF1D1B1E),
  onSurface: Color(0xFFE7E1E6),
  surfaceVariant: Color(0xFF4A454E),
  onSurfaceVariant: Color(0xFFCBC4CF),
  outline: Color(0xFF958E99),
  onInverseSurface: Color(0xFF1D1B1E),
  inverseSurface: Color(0xFFE7E1E6),
  inversePrimary: Color(0xFF773BC8),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFD7BAFF),
  outlineVariant: Color(0xFF4A454E),
  scrim: Color(0xFF000000),
);
